### ISSUE TITLE
Error message when trying to deploy lakeFS with Argo CD

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/charts#85] opened 2021-08-04 15:37 UTC
Reported by a community memeber on our Slack #help channel.

The following error appeared:
```
FailedMount MountVolume.SetUp failed for volume 'lakefs-config': configmap not found
```

Try to reproduce this issue.

**Comment by johnnyaug** [comment] 2021-08-08 07:05
Couldn't reproduce the issue with a local installation of Argo CD over microk8s - lakeFS was installed successfully.

**Comment by itaiad200** [comment] 2021-09-30 10:55
Seems to work with Argo. Closing and will reopen if this surfaces again.

**Comment by zevektor** [comment] 2022-11-28 20:45
Hello, 

I think this problem is related to EKS + Argo, because I am having the same problem. 

In addition to this, even though my serviceAccount.create setting was set to 'true', I had to manually create it. 
After creating the SA manually I am now encountering this same error.

**Comment by zevektor** [comment] 2022-11-29 08:42
I made some progress and found what causes the error:

The LakeFS migration job is failing because ArgoCD creates it before the configmap named lakefs is created.

If I stop the ArgoCD sync, manually sync the configmap only and finally sync the whole lakefs application, then it works.

**Comment by nopcoder** [comment] 2022-12-01 17:33
@zevektor we tried to reproduce it on our ArgoCD without success. Can you specify the version of ArgoCD you are using, maybe it is a specific version issue.
Also, I'm working on another task to simplify the Helm chart and probably remove the migrate job from the next version - if this is the source of the pain.
Will update here if any progress related to the second item.

**Comment by zevektor** [comment] 2022-12-02 08:11
@nopcoder I am using their helm chart version 5.13.4, which comes with version 2.5.1 of argocd. 

My underlying EKS version is 1.22

**Comment by nopcoder** [comment] 2022-12-27 11:58
@zevektor can you pull the latest and try again - the new chart doesn't include a migration job.
Want to know if this is the reason for this failure.

**Comment by nopcoder** [comment] 2023-01-04 15:42
@zevektor did it help? can I close this one?

**Comment by idanovo** [comment] 2023-01-26 10:25
@nopcoder @zevektor close it for now

**Closed by idanovo** 2023-01-26 10:25 UTC
Labels: contributor, team/cloud-native
